config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'application#index'
  get '/home', to: 'application#index'
  mount Sidekiq::Web => '/sidekiq'
  resources 'platforms'
  post '/initiatives/register', to: 'resources#register_initiative'
  get '/set_platform/:platform_id', to: 'platforms#set_instance'
  get '/resources', to: 'resources#index'
  get '/resources/cetesb_gatherer', to: 'resources#fetch_cetesb_data'
  get '/resources/accuweather_gatherer', to: 'resources#fetch_accuweather_data'
  get '/resources/citybik_gatherer', to: 'resources#fetch_citybik_data'
  get '/resources/catracalivre_gatherer', to: 'resources#fetch_catracalivre_data'
  get '/resources/active_cetesb_cron', to: 'resources#active_cetesb_cron'
  get '/dump_recovery', to: 'resources#dump_recovery'
  get '/cetesb_cron_index', to: 'crons_scheduling#cetesb_cron_index'
  get '/accuweather_cron_index', to: 'crons_scheduling#accuweather_cron_index'
  get '/citybik_cron_index', to: 'crons_scheduling#citybik_cron_index'
  get '/catracalivre_cron_index', to: 'crons_scheduling#catracalivre_cron_index'

  get '/geosampa_data', to: 'static_resources#geosampa_data'
  post '/geosampa_data', to: 'static_resources#create'

  post '/cetesb_cron_activate', to: 'crons_scheduling#cetesb_cron_activate'
  post '/accuweather_cron_activate', to: 'crons_scheduling#accuweather_cron_activate'
  post '/citybik_cron_activate', to: 'crons_scheduling#citybik_cron_activate'
  post '/catracalivre_cron_activate', to: 'crons_scheduling#catracalivre_cron_activate'

  post '/dump_and_inject', to: 'resources#dump_and_inject'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery unless: -> { request.format.json? }

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div class="ui container">
  <h1 class="ui header center aligned">
    OPENDOOR
  </h1>
</div>

app/views/application/_sidebar.html.erb
<div class="ui vertical menu">
  <div class="item">
    <div class="header">Platforms Instances</div>

    <div class="menu">
      <%= link_to "Search", platforms_path, class: "item" %>
      <%= link_to "New", new_platform_path, class: "item" %>
    </div>
  </div>

  <div class="item">
    <div class="header">Collectors</div>

    <div class="menu">
      <a class="item" href="/resources">
        Resources
      </a>

      <a class="item" href="/resources/cetesb_gatherer">
        Fetch Cetesb Data
      </a>

      <a class="item" href="/resources/accuweather_gatherer">
        Fetch Accuweather Data
      </a>

      <a class="item" href="/resources/citybik_gatherer">
        Fetch Citybik Data
      </a>

      <a class="item" href="/resources/catracalivre_gatherer">
        Fetch Catraca Livre Data
      </a>
    </div>
  </div>

  <div class="item">
    <div class="header">Static Collectors</div>

    <div class="menu">
      <a class="item" href="/geosampa_data">
        GeoSampa Data
      </a>
    </div>
  </div>

  <div class="item">
    <div class="header">Dump Recovery</div>

    <div class="menu">
      <a class="item" href="/dump_recovery">
        Inject dump in a platform
      </a>
    </div>
  </div>

  <div class="item">
    <div class="header">Crons</div>

    <div class="menu">
      <a class="item" href="/cetesb_cron_index">
        Cetesb Cron
        <% if CetesbGathererWorker.cron_running %>
          <i class="green checkmark icon"></i>
        <% else %>
          <i class="remove red icon"></i>
        <% end %>
      </a>

      <a class="item" href="/accuweather_cron_index">
        Accuweather Cron
        <% if AccuweatherGathererWorker.cron_running %>
          <i class="green checkmark icon"></i>
        <% else %>
          <i class="remove red icon"></i>
        <% end %>
      </a>

      <a class="item" href="/citybik_cron_index">
        Citybik Cron
        <% if CitybikGathererWorker.cron_running %>
          <i class="green checkmark icon"></i>
        <% else %>
          <i class="remove red icon"></i>
        <% end %>
      </a>

      <a class="item" href="/catracalivre_cron_index">
        Catraca Livre Cron
        <% if CatracalivreGathererWorker.cron_running %>
          <i class="green checkmark icon"></i>
        <% else %>
          <i class="remove red icon"></i>
        <% end %>
      </a>

    </div>
  </div>

  <div class="item">
    <div class="header">Project</div>

    <div class="menu">
      <a class="item" href="https://gitlab.com/sampadashboard/opendoor">
        Source Code
      </a>
      <a class="item" href="https://social.stoa.usp.br/poo2017/grupo-1-suporte-na-plataforma-interscity-e-coleta-de-dados">
        Stoa Page
      </a>
    </div>
  </div>
</div>

app/views/application/index.html.erb
<h1>OpenDoor</h1>